[workspace]
members = [
    "crates/pyd-core",
    "crates/pyd-parser",
    "crates/pyd-vulkan",
    "crates/pyd-cli",
]
resolver = "2"

[workspace.package]
version = "6.0.0"
edition = "2021"
authors = ["PyDead-BIB Team"]

[workspace.dependencies]
# Frontend: Parser y AST de RustPython (compatibilidad 100% Python)
rustpython-parser = "0.4.0"
rustpython-ast = "0.4.0"

# Backend: Vulkan de bajo nivel
ash = "0.38.0"

# Utilidades
log = "0.4"
env_logger = "0.11"
thiserror = "1.0"
anyhow = "1.0"
