[package]
name = "pyd-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pyd"
path = "src/main.rs"

[dependencies]
pyd-core = { path = "../pyd-core" }
pyd-gc = { path = "../pyd-gc" }
pyd-parser = { path = "../pyd-parser" }
pyd-vulkan = { path = "../pyd-vulkan" }
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
