[package]
name = "pyd-cli"
version = "6.0.0"
edition = "2021"

[[bin]]
name = "pyd"
path = "src/main.rs"

[dependencies]
pyd-core = { path = "../pyd-core" }
pyd-parser = { path = "../pyd-parser" }
pyd-vulkan = { path = "../pyd-vulkan" }

# Dependencias para modularidad y manejo profesional de CLI/Errores
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"