// ============================================================
// ADead-BIB — GCC Heritage: __builtin_*, __attribute__(()), GNU extensions
// ============================================================
// Captures everything ADead-BIB inherits from GCC:
//
//   • GCC function attributes  __attribute__((pure)), __attribute__((aligned(N)))
//   • GCC built-in functions   __builtin_expect(), __builtin_clz(), …
//   • GNU statement expressions  ({ … })  — recognised but not lowered
//   • Inline assembly keywords  __asm__
//
// References:
//   https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html
//   https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
// ============================================================

/// GCC function / variable / type attributes `__attribute__((...))`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GccAttribute {
    // ── Code-generation hints ────────────────────────────────
    /// Always inline.  Corresponds to `__attribute__((always_inline))`.
    AlwaysInline,
    /// Never inline.
    NoInline,
    /// Function is pure (no side effects, reads globals).
    Pure,
    /// Function is const (no side effects, no global reads).
    Const,
    /// Function never returns.
    NoReturn,
    /// Function result should not be discarded (warn_unused_result).
    WarnUnusedResult,
    /// Naked function — no prologue/epilogue generated by compiler.
    Naked,
    /// Function is a constructor (called before main).
    Constructor(Option<i32>),
    /// Function is a destructor (called after main).
    Destructor(Option<i32>),
    /// Cold function — optimise for size, move to cold section.
    Cold,
    /// Hot function — favour aggressive optimisation.
    Hot,

    // ── Memory / layout ─────────────────────────────────────
    /// Malloc-like allocator.
    Malloc,
    /// Pack struct with no padding.  `__attribute__((packed))`.
    Packed,
    /// Request specific alignment.  `__attribute__((aligned(N)))`.
    Aligned(u64),
    /// Mark entity as unused (suppress unused-variable warning).
    Unused,
    /// Force entity to be emitted even if unreferenced.
    Used,
    /// The type is suitable for transparent union.
    TransparentUnion,
    /// Declare the size of type in bits.
    BitfieldSize(u32),
    /// May alias any pointer type.
    MayAlias,

    // ── Visibility ──────────────────────────────────────────
    /// Symbol visibility: `"default"`, `"hidden"`, `"protected"`, `"internal"`.
    Visibility(String),
    /// Weak symbol.
    Weak,
    /// Alias for another symbol.
    Alias(String),
    /// Weak alias.
    WeakAlias(String),
    /// Weak reference.
    WeakRef,

    // ── Calling convention ──────────────────────────────────
    /// Use regular C calling convention.
    Cdecl,
    /// Use __stdcall calling convention.
    Stdcall,
    /// Use __fastcall calling convention.
    Fastcall,
    /// Use __thiscall calling convention.
    Thiscall,

    // ── printf/scanf format checking ────────────────────────
    /// printf-style format argument.  `__attribute__((format(printf, N, M)))`.
    Format {
        style: String,
        fmt_arg: u32,
        first_var: u32,
    },
    /// Similar to `format` but for strftime.
    FormatArg(u32),

    // ── Deprecation / availability ──────────────────────────
    /// Emit a deprecation warning.
    Deprecated(Option<String>),
    /// Available only on specific architecture.
    Target(String),
    /// Requires specific ISA extensions (SSE, AVX, …).
    TargetClones(Vec<String>),

    // ── Other / fallthrough ─────────────────────────────────
    /// In a switch case, this deliberately falls through.
    Fallthrough,
    /// The variable is held in a register.
    Register,
    /// Interrupt handler.
    Interrupt,
    /// Signal handler (saves/restores all regs).
    SignalHandler,
    /// Function/variable is section-placed.
    Section(String),
    /// Function should be ifunc'd.
    Ifunc(String),
    /// Unknown/unsupported attribute — stored as raw string.
    Unknown(String),
}

impl GccAttribute {
    /// Parse a single attribute name (and optional argument string).
    ///
    /// `name`  — attribute keyword, e.g. `"always_inline"`, `"aligned"`
    /// `arg`   — raw argument text if present, e.g. `"16"` for `aligned(16)`
    pub fn parse(name: &str, arg: Option<&str>) -> Self {
        match name {
            "always_inline" | "__always_inline__" => Self::AlwaysInline,
            "noinline" | "__noinline__" => Self::NoInline,
            "pure" | "__pure__" => Self::Pure,
            "const" | "__const__" => Self::Const,
            "noreturn" | "__noreturn__" => Self::NoReturn,
            "warn_unused_result" => Self::WarnUnusedResult,
            "naked" => Self::Naked,
            "constructor" => {
                let prio = arg.and_then(|a| a.parse().ok());
                Self::Constructor(prio)
            }
            "destructor" => {
                let prio = arg.and_then(|a| a.parse().ok());
                Self::Destructor(prio)
            }
            "cold" => Self::Cold,
            "hot" => Self::Hot,
            "malloc" => Self::Malloc,
            "packed" => Self::Packed,
            "aligned" => {
                let n = arg.and_then(|a| a.parse().ok()).unwrap_or(16);
                Self::Aligned(n)
            }
            "unused" => Self::Unused,
            "used" => Self::Used,
            "transparent_union" => Self::TransparentUnion,
            "may_alias" => Self::MayAlias,
            "visibility" => {
                Self::Visibility(arg.unwrap_or("default").trim_matches('"').to_string())
            }
            "weak" => Self::Weak,
            "alias" => Self::Alias(arg.unwrap_or("").trim_matches('"').to_string()),
            "weak_alias" => Self::WeakAlias(arg.unwrap_or("").trim_matches('"').to_string()),
            "weakref" => Self::WeakRef,
            "cdecl" => Self::Cdecl,
            "stdcall" => Self::Stdcall,
            "fastcall" => Self::Fastcall,
            "thiscall" => Self::Thiscall,
            "deprecated" => Self::Deprecated(arg.map(|s| s.trim_matches('"').to_string())),
            "target" => Self::Target(arg.unwrap_or("").to_string()),
            "fallthrough" => Self::Fallthrough,
            "section" => Self::Section(arg.unwrap_or("").trim_matches('"').to_string()),
            "interrupt" => Self::Interrupt,
            "signal" => Self::SignalHandler,
            other => Self::Unknown(other.to_string()),
        }
    }

    /// Whether this attribute prevents the compiler from inlining the function.
    pub fn blocks_inlining(&self) -> bool {
        matches!(
            self,
            Self::NoInline | Self::Naked | Self::Interrupt | Self::SignalHandler
        )
    }

    /// Whether this attribute forces inlining.
    pub fn forces_inlining(&self) -> bool {
        matches!(self, Self::AlwaysInline)
    }

    /// Whether this attribute changes the function's calling convention.
    pub fn is_calling_convention(&self) -> bool {
        matches!(
            self,
            Self::Cdecl | Self::Stdcall | Self::Fastcall | Self::Thiscall
        )
    }

    /// Return effective alignment in bytes (if applicable).
    pub fn alignment(&self) -> Option<u64> {
        if let Self::Aligned(n) = self {
            Some(*n)
        } else {
            None
        }
    }
}

// ── GCC Built-in Functions ──────────────────────────────────────────────────

/// GCC `__builtin_*` functions recognised by ADead-BIB.
///
/// The compiler can lower each to a direct byte sequence or simple IR
/// instruction without emitting an actual `call` to a library function.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GccBuiltin {
    // Branch prediction
    /// `__builtin_expect(expr, expected)` — hint to branch predictor.
    Expect,
    /// `__builtin_expect_with_probability(expr, expected, prob)`.
    ExpectWithProbability,
    /// `__builtin_unpredictable(expr)`.
    Unpredictable,

    // Bit manipulation
    /// `__builtin_clz(x)` — count leading zeros (32-bit).
    Clz,
    /// `__builtin_clzl(x)` — count leading zeros (64-bit).
    Clzl,
    /// `__builtin_ctz(x)` — count trailing zeros (32-bit).
    Ctz,
    /// `__builtin_ctzl(x)`.
    Ctzl,
    /// `__builtin_popcount(x)` — population count (32-bit).
    Popcount,
    /// `__builtin_popcountl(x)` — population count (64-bit).
    Popcountl,
    /// `__builtin_parity(x)` — parity bit.
    Parity,
    /// `__builtin_bswap16(x)`.
    Bswap16,
    /// `__builtin_bswap32(x)`.
    Bswap32,
    /// `__builtin_bswap64(x)`.
    Bswap64,
    /// `__builtin_ffs(x)` — find first set.
    Ffs,

    // Math
    /// `__builtin_sqrt(x)`.
    Sqrt,
    /// `__builtin_sqrtf(x)`.
    Sqrtf,
    /// `__builtin_abs(x)`.
    Abs,
    /// `__builtin_fabsf(x)` / `__builtin_fabs(x)`.
    Fabs,
    /// `__builtin_inf()`.
    Inf,
    /// `__builtin_inff()`.
    Inff,
    /// `__builtin_nan(str)`.
    Nan,
    /// `__builtin_huge_val()`.
    HugeVal,
    /// `__builtin_fma(x, y, z)`.
    Fma,

    // Memory
    /// `__builtin_memcpy(dest, src, n)`.
    Memcpy,
    /// `__builtin_memmove(dest, src, n)`.
    Memmove,
    /// `__builtin_memset(dest, c, n)`.
    Memset,
    /// `__builtin_memcmp(s1, s2, n)`.
    Memcmp,
    /// `__builtin_strlen(s)`.
    Strlen,
    /// `__builtin_strcmp(s1, s2)`.
    Strcmp,
    /// `__builtin_strcpy(dest, src)`.
    Strcpy,
    /// `__builtin_alloca(size)`.
    Alloca,
    /// `__builtin_alloca_with_align(size, align)`.
    AllocaWithAlign,

    // Stack / frame
    /// `__builtin_return_address(level)`.
    ReturnAddress,
    /// `__builtin_frame_address(level)`.
    FrameAddress,
    /// `__builtin_stack_address()`.
    StackAddress,

    // Type / classify
    /// `__builtin_types_compatible_p(T1, T2)`.
    TypesCompatibleP,
    /// `__builtin_choose_expr(cond, e1, e2)`.
    ChooseExpr,
    /// `__builtin_classify_type(x)`.
    ClassifyType,
    /// `__builtin_offsetof(T, field)`.
    Offsetof,

    // Control flow
    /// `__builtin_unreachable()`.
    Unreachable,
    /// `__builtin_trap()`.
    Trap,
    /// `__builtin_abort()`.
    Abort,

    // Atomic (GCC __sync_* family)
    /// `__sync_fetch_and_add(ptr, val)`.
    SyncFetchAndAdd,
    /// `__sync_fetch_and_sub(ptr, val)`.
    SyncFetchAndSub,
    /// `__sync_fetch_and_or(ptr, val)`.
    SyncFetchAndOr,
    /// `__sync_fetch_and_and(ptr, val)`.
    SyncFetchAndAnd,
    /// `__sync_fetch_and_xor(ptr, val)`.
    SyncFetchAndXor,
    /// `__sync_lock_test_and_set(ptr, val)`.
    SyncLockTestAndSet,
    /// `__sync_lock_release(ptr)`.
    SyncLockRelease,
    /// `__sync_bool_compare_and_swap(ptr, old, new)`.
    SyncBoolCompareAndSwap,
    /// `__sync_val_compare_and_swap(ptr, old, new)`.
    SyncValCompareAndSwap,

    // Overflow-checked arithmetic (C11 __builtin_add_overflow etc.)
    /// `__builtin_add_overflow(a, b, res)`.
    AddOverflow,
    /// `__builtin_sub_overflow(a, b, res)`.
    SubOverflow,
    /// `__builtin_mul_overflow(a, b, res)`.
    MulOverflow,

    // Prefetch / cache
    /// `__builtin_prefetch(addr, rw, locality)`.
    Prefetch,
    /// `__builtin_ia32_clflush(addr)`.
    Clflush,

    // Misc
    /// `__builtin_constant_p(x)` — 1 if compile-time constant.
    ConstantP,
    /// `__builtin_va_arg(list, type)`.
    VaArg,
    /// `__builtin_va_start(list, last)`.
    VaStart,
    /// `__builtin_va_end(list)`.
    VaEnd,
    /// `__builtin_va_copy(dest, src)`.
    VaCopy,
    /// Unknown `__builtin_*` — stored verbatim.
    Unknown(String),
}

impl GccBuiltin {
    /// Try to recognise a `__builtin_*` name.
    pub fn parse(name: &str) -> Self {
        let name = name.trim_start_matches("__builtin_");
        match name {
            "expect" => Self::Expect,
            "expect_with_probability" => Self::ExpectWithProbability,
            "unpredictable" => Self::Unpredictable,
            "clz" => Self::Clz,
            "clzl" | "clzll" => Self::Clzl,
            "ctz" => Self::Ctz,
            "ctzl" | "ctzll" => Self::Ctzl,
            "popcount" => Self::Popcount,
            "popcountl" | "popcountll" => Self::Popcountl,
            "parity" => Self::Parity,
            "bswap16" => Self::Bswap16,
            "bswap32" => Self::Bswap32,
            "bswap64" => Self::Bswap64,
            "ffs" => Self::Ffs,
            "sqrt" => Self::Sqrt,
            "sqrtf" => Self::Sqrtf,
            "abs" => Self::Abs,
            "fabs" | "fabsf" => Self::Fabs,
            "inf" => Self::Inf,
            "inff" => Self::Inff,
            "nan" => Self::Nan,
            "huge_val" => Self::HugeVal,
            "fma" => Self::Fma,
            "memcpy" => Self::Memcpy,
            "memmove" => Self::Memmove,
            "memset" => Self::Memset,
            "memcmp" => Self::Memcmp,
            "strlen" => Self::Strlen,
            "strcmp" => Self::Strcmp,
            "strcpy" => Self::Strcpy,
            "alloca" => Self::Alloca,
            "alloca_with_align" => Self::AllocaWithAlign,
            "return_address" => Self::ReturnAddress,
            "frame_address" => Self::FrameAddress,
            "stack_address" => Self::StackAddress,
            "types_compatible_p" => Self::TypesCompatibleP,
            "choose_expr" => Self::ChooseExpr,
            "classify_type" => Self::ClassifyType,
            "offsetof" => Self::Offsetof,
            "unreachable" => Self::Unreachable,
            "trap" => Self::Trap,
            "abort" => Self::Abort,
            "add_overflow" => Self::AddOverflow,
            "sub_overflow" => Self::SubOverflow,
            "mul_overflow" => Self::MulOverflow,
            "prefetch" => Self::Prefetch,
            "constant_p" => Self::ConstantP,
            "va_arg" => Self::VaArg,
            "va_start" => Self::VaStart,
            "va_end" => Self::VaEnd,
            "va_copy" => Self::VaCopy,
            other => Self::Unknown(other.to_string()),
        }
    }

    /// Whether this builtin can be replaced with an inline instruction sequence.
    pub fn is_inlinable(&self) -> bool {
        matches!(
            self,
            Self::Expect
                | Self::Clz
                | Self::Clzl
                | Self::Ctz
                | Self::Ctzl
                | Self::Popcount
                | Self::Popcountl
                | Self::Bswap16
                | Self::Bswap32
                | Self::Bswap64
                | Self::Sqrt
                | Self::Sqrtf
                | Self::Memcpy
                | Self::Memset
                | Self::Unreachable
                | Self::Trap
                | Self::ConstantP
        )
    }

    /// Generate raw x86-64 bytes for trivial builtins (best-effort).
    ///
    /// Returns `Some(bytes)` for builtins that always emit fixed sequences,
    /// `None` if the builtin needs context (operands, registers, …).
    pub fn quick_encode(&self) -> Option<Vec<u8>> {
        match self {
            // ud2 — undefined instruction, used for unreachable/trap
            Self::Unreachable | Self::Trap => Some(vec![0x0F, 0x0B]),
            // int3 — software breakpoint
            Self::Abort => Some(vec![0xCC]),
            _ => None,
        }
    }
}
